apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: routing-service
build:
  artifacts:
  - image: gcr.io/votiethuy/athena
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
portForward:
  - resourceType: service
    resourceName: athena
    port: 5000

profiles:
- name: gke
  build:
    googleCloudBuild:
      projectId: zendesk-293508
