  
apiVersion: v1
kind: Service
metadata:
  name: athena
spec:
  ports:
  - port: 5000
    name: http
  type: LoadBalancer
  selector:
    app: athena
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena
spec:
  selector:
    matchLabels:
      app: athena
  template:
    metadata:
      labels:
        app: athena
    spec:
      containers:
      - name: athena
        image: athena
        env:
          - name: PORT
            value: "5000"
        ports:
          - containerPort: 5000
        livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
        readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 1Gi
            cpu: 1
